### ISSUE TITLE
滚动不准确

### ISSUE THREAD

**Issue by lizhuangs** [abc1310054026/sync-scroll#1]
右边滚动到了Usage的时候，左侧源码中已经看不到了。这一点有道云笔记和vscode做得挺不错的。

**Comment by abc1310054026** [comment]
嗯，我已经更新了项目，你可以在你的浏览器上再试试。
有可能之前的代码有错误，但是我是在push完了之后才看到你的issues，所以没办法复现了。

**Comment by lizhuangs** [comment]
显示还是有问题，但是我想了一下，左右的代码再怎么滚动都会出现有一边显示不全的情况，因为两边的内容不是完全一样的。由于你这个演示界面左侧不能编辑，建议添加编辑功能，当光标在左侧点击某一行的时候，右侧滚动到相应的位置。

**Comment by abc1310054026** [comment]
嗯 我加了点击同步，点击标题可以准确地对齐，点内容的话只能按标题下内容的百分比对齐，就会不太准。
